rails/task-timer/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'

  get 'pages/about'

  get 'pages/directions'

  resources :tasks do
    resources :comments
    resources :timers
  end

  resources :projects

  root 'pages#home'
  
end

rails/task-timer/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :comments, dependent: :destroy
  has_many :timers, dependent: :destroy

  validates :name, presence: true
  validates :description, length: { maximum: 500 }
  validates :project_id, presence: true

  def closed_timers
    self.timers.where.not(finish: nil)
  end

  def last_open_timer
    self.timers.where(finish: nil).last
  end
end

rails/task-timer/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @task = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def start_timer

  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      @task.save
      format.js
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])

      @timers = @task.closed_timers
      @timer = @task.last_open_timer || @task.timers.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      form_params = params.require(:task).permit(:name, :description, :project_id)
      form_params.merge!( { project_id: params.require(:project)[:id] } )
    end
end

rails/task-timer/app/helpers/tasks_helper.rb
require 'time_diff'

module TasksHelper

  def delta_time ( start, finish )
    Time.diff( start, finish, '%h:%m:%s' )[:diff]
  end

end

rails/task-timer/app/views/tasks/_form.html.haml
= form_for(@task, remote: true) do |f|
  - if @task.errors.any?
    #error_explanation
      %h2
        = pluralize(@task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message
  .input-field
    = f.text_field :name, { class: "validate"}
    = f.label :name
  .input-field
    = f.text_field :description, { class: "validate"}
    = f.label :description
  .input-field
    = select("project", "id", Project.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Project'})
    = f.label :project
  .input-field
    = f.submit 'Create Task', { class: "btn waves-effect waves-light" }

rails/task-timer/app/views/tasks/_task.html.haml
= content_tag_for :tr, task, class: "#{cycle('odd', 'even')}" do
    %td= link_to task.name, task
    %td= link_to task.project.name, task.project
    %td= link_to 'Edit', edit_task_path(task)
    %td= link_to 'Destroy', task, method: :delete, remote: true

rails/task-timer/app/views/tasks/create.js.erb
$('tbody#tasks').append(' <%= escape_javascript(render @task) %>');
$('form#new_task').trigger('reset');

rails/task-timer/app/views/tasks/destroy.js.erb
$('#<%= dom_id(@task) %>').fadeOut();

rails/task-timer/app/views/tasks/edit.html.haml
.row
  .col.s12
    %h1 Editing Task
    = render 'form'
    = link_to 'Show', @task
    |
    = link_to 'Back', tasks_path

rails/task-timer/app/views/tasks/index.html.haml
.row
  .col.s12.m8.offset-m2
    %p#notice= notice
    %h1 Listing Tasks

    %table
      %thead
        %tr
          %th Name
          %th Project
          %th{ colspan: "3"}
      %tbody#tasks
        = render @tasks
    %br

    = render 'form'

rails/task-timer/app/views/tasks/new.html.haml
.row
  .col.s12
    %h1 New Task
    = render 'form'
    = link_to 'Back', tasks_path

rails/task-timer/app/views/tasks/show.html.haml
- provide :title, "Tasks"
.row
  .col.s12.m8.offset-m2

    .card
      .card-content
        %p
          %strong Name:
          = @task.name
        %p
          %strong Description:
          = @task.description
        %p
          %strong Project:
          = link_to @task.project.name, @task.project

    - if user_signed_in?
      .card
        .card-content
          .row
            .col.s2
              #timer-form-wrapper
                = render "timers/form", timer: @timer, task: @task
            .col.s10#card-timer
              %span#timer.card-title

      .card
        .card-content#timers-card
          %span.card-title Timers
          = render @timers

    - if @task.comments.any?
      %h4 Comments
      - @task.comments.each do |comment|
        .card
          .card-content
            %span.card-title
              =comment.author
            %p
              = comment.body
            %p
              = link_to [@task, comment], method: :delete do
                %i.material-icons delete


    .card
      .card-content
        %span.card-title Add a Comment
        = form_for [@task, @task.comments.build] do |f|
          .input-field
            = f.text_field :author
            = f.label :author
          .input-field
            = f.text_area :body, { class: "materialize-textarea" }
            = f.label :body
          .input-field
            = f.submit "Submit Comment", { class: "btn waves-effect waves-light"}
    %br
    = link_to 'Edit', edit_task_path(@task), class: 'btn waves-effect waves-light'
    = link_to 'Back', tasks_path, class: 'btn waves-effect waves-light'