rails/task-timer/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'

  get 'pages/about'

  get 'pages/directions'

  resources :tasks do
    resources :comments
    resources :timers
  end

  resources :projects

  root 'pages#home'
  
end

rails/task-timer/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= yield(:title)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'icon_32.png'
  %body
    %header
      %nav.nav-wrapper
        = link_to image_tag( "icon_128.png", alt: "Task Timer" ), pages_home_path,
              class: 'brand-logo left'
        %ul#nav-mobile.right

          %li
            = link_to "Home", pages_home_path
          - if user_signed_in?
            %li
              = link_to "Projects", projects_path
            %li
              = link_to "Tasks", tasks_path
          %li
            = link_to "About", pages_about_path
          - if not user_signed_in?
            %li= link_to "Sign up", new_user_registration_path
            %li= link_to "Sign in", new_user_session_path
          - else
            %li= link_to "Sign out", destroy_user_session_path, method: :delete
    #wrapper
      %input#notice{type: "hidden", value: "#{notice}"}
      %input#alert{type: "hidden", value: "#{alert}"}

      = yield