rails/task-timer/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'

  get 'pages/about'

  get 'pages/directions'

  resources :tasks do
    resources :comments
    resources :timers
  end

  resources :projects

  root 'pages#home'
  
end

rails/task-timer/app/models/timer.rb
class Timer < ActiveRecord::Base
  scope :recent, ->(num=10) { order(created_at: :desc).limit num }
  scope :by_task, ->(task) { where(task_id: task) }
  scope :open, -> { where(finish: nil) }
  scope :closed, -> { where.not(start: nil, finish: nil) }

  belongs_to :task
end

rails/task-timer/app/controllers/timers_controller.rb
class TimersController < ApplicationController
  before_action :set_timer, only: [:update, :edit, :destroy]
  before_action :authenticate_user!
  def new
  end

  def create
    @task = Task.find params[:task_id]

    @timer = @task.timers.create(timer_params)
    respond_to do |format|
      # format.html { redirect_to @task, notice: 'Timer started' }
      format.json { render json: @timer.to_json(except: [:created_at, :updated_at]) }
      format.js
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @timer.update timer_params
        # format.html { redirect_to @task, notice: 'Timer stopped' }
        format.json { render json: @timer.to_json(except: [:created_at, :updated_at]) }
        format.js
      end
    end

  end

  def destroy
    respond_to do |format|
      if @timer.destroy
        format.json { render json: {success: true} }
        format.js
      end
    end
  end

  private
    def set_timer
      @timer = Timer.find(params[:id])
      @task = @timer.task
    end

    def timer_params
      form_params = params.require(:timer).permit :start, :finish
    end

end

rails/task-timer/app/helpers/timers_helper.rb
module TimersHelper

  def display_time(time)
    # TODO
  end
end

rails/task-timer/app/views/timers/_form.html.haml
= form_for [task, timer],
    html: { id: 'timer-form'}, remote: true do |f|
  - if @timer.errors.any?
    #error_explanation
      %h2
        = pluralize(@timer.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - @timer.errors.full_messages.each do |message|
          %li= message
  = f.hidden_field :start, {id: 'time-start'}
  = f.hidden_field :finish, {id: 'time-finish'}

  = button_tag type: :submit, class: " red btn-large btn-floating waves-effect waves-light", id: "timer-button" do
    %i.material-icons.right#timer-button-icon
      - if timer.start
        stop
      - else
        play_arrow

rails/task-timer/app/views/timers/_timer.html.haml
= content_tag_for :div, timer, class: "row" do
  .col.s3
    = timer.start.to_s( :db )
  .col.s3
    = timer.finish.to_s( :db )
  .col.s3
    = delta_time timer.start, timer.finish
  .col.s3
    = link_to task_timer_path(@task.id, timer.id), remote: true, method: :delete, class: "destroy-timer" do
      %i.material-icons delete